import { seoHead } from './seo.js';
import { languages, translations, projects } from './content.js';
import nodeProcess from 'node:process';
import { faWordpress, faShopify, faHtml5, faCss3Alt, faJs, faGulp, faGitAlt } from '@fortawesome/free-brands-svg-icons';
export const escape = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export function href(lang, route = '') {
  const base = (nodeProcess.env.SITE_PATH_PREFIX || '/').replace(/\/$/, '');
  return `${base}/${lang === 'en' ? '' : lang + '/'}${route ? route.replace(/^\/|\/$/g, '') + '/' : ''}`;
}
export function asset(path) { return `${(nodeProcess.env.SITE_PATH_PREFIX || '/').replace(/\/$/, '')}/assets/${path}`; }
export const arrow = '<span aria-hidden="true">↗</span>';
export function icon(name = 'code') {
  const paths = { code: '<path d="m8 7-5 5 5 5m8-10 5 5-5 5m-3-14-2 18"/>', speed: '<path d="m13 2-9 12h7l-1 8 10-12h-7z"/>', screen: '<rect x="2" y="3" width="15" height="12" rx="2"/><path d="M6 19h7m-3-4v4"/><rect x="17" y="9" width="5" height="12" rx="1"/>', check: '<path d="m5 12 4 4L19 6"/>', chat: '<path d="M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4Z"/>', grid: '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>', globe: '<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>', bag: '<path d="M4 7h16l1 14H3Zm4 0V6a4 4 0 0 1 8 0v1"/>' };
  return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.code}</svg>`;
}
export function button(label, url, primary = false) { return `<a class="btn ${primary ? 'btn-primary' : ''}" href="${escape(url)}">${escape(label)}${arrow}</a>`; }
export function heading(kicker, title, text = '') { return `<div class="max-w-3xl"><p class="eyebrow">${escape(kicker)}</p><h1>${title}</h1>${text ? `<p class="mt-6 max-w-2xl text-lg">${escape(text)}</p>` : ''}</div>`; }
export function cta(lang) { const t = translations[lang]; return `<section class="wrap pb-16"><div class="panel flex flex-col gap-8 p-8 md:flex-row md:items-center md:justify-between lg:p-10"><div class="max-w-xl"><p class="eyebrow">${escape(t.nav[4])}</p><h2>${escape(t.cta)}</h2><p class="mt-4">${escape(t.ctaText)}</p></div>${button(t.write, href(lang, 'contacts'), true)}</div></section>`; }
export function card(project, lang) {
  const t = translations[lang]; const i = projects.indexOf(project);
  if (project.real) return `<article class="panel project-card transition-transform" data-project data-categories="${project.filters.join(' ')}"><a class="block p-3" href="${href(lang,'portfolio/'+project.slug)}" tabindex="-1" aria-hidden="true"><img class="rounded-lg" src="${asset(project.image)}" alt="" width="1200" height="833" loading="lazy"></a><div class="px-6 pb-6"><p class="mb-3 text-xs uppercase tracking-widest text-accent">${escape(project.labels[lang].badge)}</p><h3><a href="${href(lang,'portfolio/'+project.slug)}">${escape(project.name[lang])}</a></h3><div class="my-3 flex flex-wrap gap-2">${project.tech.map(v=>`<span class="tag">${escape(v)}</span>`).join('')}</div><p>${escape(project.description[lang])}</p><a class="mt-6 inline-flex min-h-11 items-center gap-3 text-sm text-accent hover:text-accent-hover" href="${href(lang,'portfolio/'+project.slug)}">${escape(t.more)}${arrow}</a></div></article>`;
  return `<article class="panel project-card transition-transform" data-project data-categories="${project.filters.join(' ')}"><a class="block p-3" href="${href(lang, 'portfolio/' + project.slug)}" tabindex="-1" aria-hidden="true"><img class="rounded-lg" src="${asset(project.slug + '-home.svg')}" alt="" width="800" height="500" loading="lazy"></a><div class="px-6 pb-6"><p class="mb-3 text-xs uppercase tracking-widest text-accent">${escape(t.demo)}</p><h3><a href="${href(lang, 'portfolio/' + project.slug)}">${escape(t.projectNames[i])}</a></h3><div class="my-3 flex flex-wrap gap-2">${project.tech.map(v => `<span class="tag">${escape(v)}</span>`).join('')}</div><p>${escape(t.projectDescriptions[i])}</p><a class="mt-6 inline-flex min-h-11 items-center gap-3 text-sm text-accent hover:text-accent-hover" href="${href(lang, 'portfolio/' + project.slug)}">${escape(t.more)}${arrow}</a></div></article>`;
}
export function cards(list, lang) { return `<div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">${list.map(p => card(p, lang)).join('')}</div>`; }
export function process(lang) {
  const t = translations[lang]; return `<div><p class="eyebrow">${escape(t.process)}</p><h2 class="mb-8">${escape(t.processTitle)}</h2><ol class="grid gap-8 sm:grid-cols-2">${t.steps.map((v, i) => `<li class="flex gap-4"><span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-accent/10 font-mono text-accent">0${i + 1}</span><div><h3 class="text-lg">${escape(v)}</h3><p class="mt-2 text-sm">${escape(t.stepText[i])}</p></div></li>`).join('')}</ol></div>`;
}
export function technologies(lang) {
  const t = translations[lang]; const names = ['WordPress', 'Shopify', 'HTML5', 'CSS / SCSS', 'JavaScript', 'Gulp / npm', 'Git / GitHub'];
  const marks = [faWordpress, faShopify, faHtml5, faCss3Alt, faJs, faGulp, faGitAlt];
  return `<div class="grid grid-cols-2 gap-8 text-center sm:grid-cols-3 lg:grid-cols-7">${names.map((n, i) => { const [width,height,,,paths] = marks[i].icon; return `<div><span class="tech-icon" aria-hidden="true"><svg viewBox="0 0 ${width} ${height}" fill="currentColor" focusable="false">${(Array.isArray(paths)?paths:[paths]).map(d=>`<path d="${d}"/>`).join('')}</svg></span><h3 class="text-base">${n}</h3><p class="mt-2 text-sm">${escape(t.techDescriptions[i])}</p></div>`; }).join('')}</div>`;
}
export function layout(content, {lang = 'en', route = '', title, description, site, noindex = false}) {
  const t = translations[lang]; const routes = ['', 'about', 'services', 'portfolio', 'contacts']; const current = route.split('/')[0];
  const themeSwatches = `<div class="theme-swatches" role="group" aria-label="${escape(t.theme)}">${['blue','green','yellow','red','purple'].map((color,i)=>`<button type="button" class="theme-swatch" data-accent-choice="${color}" aria-label="${escape(t.themeColors[i])}" title="${escape(t.themeColors[i])}" aria-pressed="false"></button>`).join('')}</div>`;
  const themePicker = `<div class="hidden xl:block"><button type="button" class="theme-trigger" popovertarget="theme-picker" aria-label="${escape(t.theme)}" title="${escape(t.theme)}"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="12" cy="12" r="9"/><circle cx="8" cy="8" r="1"/><circle cx="15" cy="7" r="1"/><circle cx="18" cy="13" r="1"/><path d="M7 16c4-4 8 0 5 4"/></svg></button><div id="theme-picker" popover class="theme-popover"><p class="mb-4 text-sm">${escape(t.theme)}</p>${themeSwatches}</div></div>`;
  const navigation = routes.map((r, i) => `<a class="nav-link" href="${href(lang, r)}"${r === current ? ' aria-current="page"' : ''}>${escape(t.nav[i])}</a>`).join('');
  const languageLinks = languages.map(l => `<a class="px-2 py-2 text-xs ${l === lang ? 'text-accent' : 'text-muted hover:text-ink'}" href="${href(l, route)}" lang="${l}" hreflang="${l}"${l === lang ? ' aria-current="true"' : ''}>${l === 'uk' ? 'UA' : l.toUpperCase()}</a>`).join('');
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${seoHead({lang, route, site, title, description, noindex, href, escape})}<meta name="theme-color" content="#080b0f"><link rel="icon" href="${asset('favicon.svg')}" type="image/svg+xml"><script src="${asset('theme.js')}"></script><link rel="stylesheet" href="${asset('site.css')}"><script type="module" src="${asset('site.js')}"></script></head><body id="top" data-cookie-path="${escape(href('en'))}"><a class="fixed left-4 top-4 z-50 -translate-y-24 rounded-lg bg-accent px-6 py-3 focus:translate-y-0" href="#main">${escape(t.skip)}</a><header class="site-header"><div class="wrap header-row"><a class="header-brand" href="${href(lang)}">Extended <span class="text-accent">Solution</span></a><nav class="hidden items-center gap-6 xl:flex" aria-label="${escape(t.menu)}">${navigation}</nav><div class="flex items-center gap-3">${themePicker}<div class="hidden sm:flex" aria-label="Language">${languageLinks}</div><a class="btn hidden lg:inline-flex" href="${href(lang, 'contacts')}">${escape(t.write)}${arrow}</a><button class="menu-toggle xl:hidden" id="menu-toggle" aria-haspopup="dialog" aria-controls="mobile-menu" aria-expanded="false"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg><span class="sr-only">${escape(t.menu)}</span></button></div><dialog id="mobile-menu" class="mobile-drawer" aria-labelledby="drawer-title"><div class="mb-8 flex items-center justify-between gap-4"><span id="drawer-title" class="text-lg font-semibold">${escape(t.menu)}</span><button id="menu-close" class="drawer-close" aria-label="${escape(t.close)}"><span aria-hidden="true">×</span></button></div><nav class="flex flex-col gap-2" aria-label="${escape(t.menu)}">${navigation}</nav><div class="mt-8 flex gap-3 border-t border-line pt-6" aria-label="Language">${languageLinks}</div><div class="mt-8"><p class="mb-3 text-sm">${escape(t.theme)}</p>${themeSwatches}</div><div class="mt-8">${button(t.write, href(lang, 'contacts'), true)}</div></dialog></div></header><main id="main">${content}</main><footer class="wrap"><div class="flex flex-col gap-6 border-t border-line py-8 sm:flex-row sm:items-center sm:justify-between"><div><a class="text-lg font-semibold" href="${href(lang)}">Extended <span class="text-accent">Solution</span></a><p class="mt-2 text-xs">Web Developer / WordPress / Shopify / JavaScript</p></div><div class="flex items-center gap-6"><p class="text-xs">© ${new Date().getFullYear()} ${escape(site.name)}</p><a class="btn min-h-11 px-4" href="#top" aria-label="${escape(t.top)}"><span aria-hidden="true">↑</span></a></div></div></footer></body></html>`;
}
