import { languages, translations, projects } from './lib/content.js';
import { escape, href, asset, icon, button, heading, cta, cards, process, technologies, layout } from './lib/ui.js';
const routes = ['', 'about', 'portfolio', 'services', 'contacts', ...projects.map(p => 'portfolio/' + p.slug)];
export default class Pages {
  data() {
    return {
      pagination: { data: 'variants', size: 1, alias: 'variant' },
      variants: languages.flatMap(lang => routes.map(route => ({lang, route}))),
      permalink: ({ variant: { lang, route } }) => `${lang === 'en' ? '' : lang + '/'}${route ? route + '/' : ''}index.html`
    };
  }
  render({ variant: { lang, route }, site }) {
    const t = translations[lang]; let content, title, description;
    if (!route) {
      title = t.nav[0]; description = t.intro;
      content = `<section class="wrap section grid items-center gap-10 lg:grid-cols-2"><div><p class="eyebrow">WEB / E-COMMERCE DEVELOPER</p><h1>${t.hero}</h1><p class="mt-6 max-w-xl text-lg">${escape(t.intro)}</p><div class="mt-8 flex flex-wrap gap-3">${button(t.discuss, href(lang, 'contacts'), true)}${button(t.view, href(lang, 'portfolio'))}</div><ul class="mt-10 flex flex-wrap gap-x-5 gap-y-4">${t.benefits.map((v, i) => `<li class="flex items-center gap-2 text-xs text-muted"><span class="text-accent">${icon(['speed','screen','code'][i])}</span>${escape(v)}</li>`).join('')}</ul></div><div class="relative"><img class="aspect-[3/2] w-full rounded-xl object-cover" src="${asset('workspace.webp')}" alt="${escape(t.tech)}: laptop, code editor" width="1536" height="1024" fetchpriority="high"><div class="mt-4 flex justify-between font-mono text-xs text-muted"><span>01 / WORKSPACE</span><span>DESIGN → CODE → LAUNCH</span></div></div></section><section class="section border-y border-line bg-panel"><div class="wrap"><div class="mb-10 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><h2>${escape(t.tech)}</h2><p class="max-w-md">${escape(t.techIntro)}</p></div>${technologies(lang)}</div></section><section class="wrap section"><div class="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p class="eyebrow">${escape(t.nav[3])}</p><h2>${escape(t.latest)}</h2></div><a class="text-sm text-accent" href="${href(lang,'portfolio')}">${escape(t.allProjects)} ${icon('code')}</a></div><p class="mb-6 text-sm">${escape(t.demoNote)}</p>${cards([...projects.filter(p=>p.real),...projects.filter(p=>!p.real)].slice(0,3),lang)}</section><section class="section border-t border-line bg-panel"><div class="wrap grid gap-14 lg:grid-cols-2"><div class="lg:border-r lg:border-line lg:pr-12"><p class="eyebrow">${escape(t.about)}</p><h2>${escape(t.who)}</h2><p class="mt-6 mb-8">${escape(t.aboutText)}</p>${button(t.aboutMore,href(lang,'about'))}</div>${process(lang)}</div></section>${cta(lang)}`;
    } else if (route === 'about') {
      title = t.about; description = t.aboutText;
      const metrics = [site.metrics.years, site.metrics.projects, site.metrics.specializations];
      content = `<section class="wrap section grid gap-12 lg:grid-cols-2"><div>${heading(t.about,escape(t.aboutTitle),t.aboutText)}<p class="mt-6">${escape(t.techIntro)}</p></div><div class="panel flex min-h-72 flex-col justify-center gap-8 p-10"><span class="font-mono text-accent text-sm">&lt;developer /&gt;</span><h2>${t.approach}</h2><div class="flex flex-wrap gap-2">${['WordPress','Shopify','JavaScript'].map(v=>`<span class="tag">${v}</span>`).join('')}</div></div></section><section class="wrap pb-16"><div class="grid gap-6 sm:grid-cols-3">${metrics.map((v,i)=>`<div class="border-t border-line py-6"><strong class="text-3xl text-accent">${escape(v ?? t.pending)}</strong><p class="mt-3 text-sm">${escape(t.metrics[i])}</p></div>`).join('')}</div></section><section class="section bg-panel border-y border-line"><div class="wrap"><h2>${escape(t.skills)}</h2><p class="mt-4 mb-10">${escape(t.skillIntro)}</p>${technologies(lang)}</div></section><section class="wrap section"><h2>${escape(t.experience)}</h2>${site.experience.length ? `<ol class="mt-8 border-l border-line pl-6">${site.experience.map(e=>`<li class="mb-8"><p class="text-sm text-accent">${escape(e.period)}</p><h3 class="mt-2">${escape(e.role[lang])}</h3><p class="mt-3">${escape(e.description[lang])}</p></li>`).join('')}</ol>` : `<p class="mt-6 max-w-2xl">${escape(t.experienceNote)}</p>`}<div class="mt-16 grid gap-6 md:grid-cols-2">${t.principles.map((v,i)=>`<article class="panel p-8"><span class="mb-5 block text-accent">${icon(['code','chat','screen','check'][i])}</span><h3>${escape(v)}</h3><p class="mt-3">${escape(t.principleText[i])}</p></article>`).join('')}</div></section>${cta(lang)}`;
    } else if (route === 'portfolio') {
      title = t.portfolioTitle; description = t.portfolioIntro;
      content = `<section class="wrap section">${heading(t.nav[3],escape(t.portfolioTitle),t.portfolioIntro)}<p class="mt-5 text-sm">${escape(t.demoNote)}</p><div class="my-10 flex flex-wrap gap-3" role="group" aria-label="${escape(t.nav[3])}">${t.filters.map((v,i)=>`<button class="btn filter" data-filter="${['all','wordpress','shopify','landing','store'][i]}" aria-pressed="${i===0}">${escape(v)}</button>`).join('')}</div><p class="mb-5 text-sm" aria-live="polite" id="filter-status">${projects.length} ${escape(t.results)}</p><div id="project-grid" data-results-label="${escape(t.results)}">${cards([...projects.filter(p=>p.real),...projects.filter(p=>!p.real)],lang)}</div><noscript><p class="mt-4">${escape(t.demoNote)}</p></noscript></section>${cta(lang)}`;
    } else if (route === 'services') {
      title = t.nav[2]; description = t.servicesIntro;
      content = `<section class="wrap section">${heading(t.nav[2],t.servicesTitle,t.servicesIntro)}<div class="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">${t.serviceNames.map((v,i)=>`<article class="panel flex flex-col p-8"><span class="mb-6 text-accent">${icon(['code','bag','grid','speed','screen','chat'][i])}</span><h3>${escape(v)}</h3><p class="mt-4 mb-6 grow">${escape(t.serviceText[i])}</p><a class="inline-flex min-h-11 items-center gap-3 text-sm text-accent" href="${href(lang,'contacts')}">${escape(t.discuss)}${'<span aria-hidden="true">↗</span>'}</a></article>`).join('')}</div><p class="mt-6 text-sm">${escape(t.pricing)}</p></section><section class="section bg-panel border-y border-line"><div class="wrap">${process(lang)}</div></section>${cta(lang)}`;
    } else if (route === 'contacts') {
      title = t.nav[4]; description = t.contactIntro;
      const strings = JSON.stringify({required:t.required,emailError:t.emailError,unavailable:t.unavailable,sending:t.sending,success:t.success,failure:t.failure});
      const contactLinks = [site.contacts.email ? `<a class="text-accent break-all" href="mailto:${escape(site.contacts.email)}">${escape(site.contacts.email)}</a>` : '', site.contacts.telegram ? `<a class="text-accent break-all" href="${escape(site.contacts.telegram)}">Telegram</a>` : ''].filter(Boolean);
      content = `<section class="wrap section">${heading(t.nav[4],t.contactTitle,t.contactIntro)}<div class="mt-12 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><h2 class="text-2xl">${escape(t.channels)}</h2><div class="mt-5 flex flex-col gap-4">${contactLinks.length ? contactLinks.join('') : `<p>${escape(t.channelsNote)}</p>`}</div>${site.contacts.preferred?`<p class="mt-4">${escape(site.contacts.preferred)}</p>`:''}<div class="mt-10 border-t border-line pt-8"><h3>${escape(t.process)}</h3><p class="mt-4">${escape(t.ctaText)}</p></div></div><form class="panel p-6 sm:p-8" id="contact-form" data-endpoint="${escape(site.formEndpoint)}" data-strings="${escape(strings)}" novalidate><p class="mb-6 rounded-lg border border-line p-4 text-sm" id="form-note">${escape(site.formEndpoint ? t.contactIntro : t.formNote)}</p><div class="grid gap-6 sm:grid-cols-2">${[['name',t.name,'text','name'],['email',t.email,'email','email']].map(([id,label,type,auto])=>`<div><label class="mb-2 block text-sm" for="${id}">${escape(label)} <span class="text-accent" aria-hidden="true">*</span></label><input id="${id}" name="${id}" type="${type}" autocomplete="${auto}" maxlength="${id==='name'?100:254}" required aria-describedby="${id}-error"><p class="field-error" id="${id}-error" hidden></p></div>`).join('')}</div><div class="mt-6"><label class="mb-2 block text-sm" for="type">${escape(t.type)}</label><select id="type" name="type"><option value="">${escape(t.select)}</option>${t.serviceNames.map((v,i)=>`<option value="${i}">${escape(v)}</option>`).join('')}</select></div><div class="mt-6"><label class="mb-2 block text-sm" for="message">${escape(t.message)} <span class="text-accent" aria-hidden="true">*</span></label><textarea rows="6" id="message" name="message" maxlength="5000" required aria-describedby="message-error"></textarea><p class="field-error" id="message-error" hidden></p></div><button type="submit" class="btn btn-primary mt-6">${escape(t.send)}</button><p class="mt-5" id="form-status" role="status" tabindex="-1"></p><noscript><p class="mt-4">${escape(t.unavailable)}</p></noscript></form></div></section>`;
    } else if (projects.some(p=>p.real && route === 'portfolio/'+p.slug)) {
      const p = projects.find(p=>route === 'portfolio/'+p.slug); const labels = p.labels[lang];
      title = p.name[lang]; description = p.description[lang];
      content = `<section class="wrap section"><a class="mb-8 inline-flex min-h-11 items-center gap-3 text-sm text-muted hover:text-accent" href="${href(lang,'portfolio')}">← ${escape(t.back)}</a><div class="grid items-center gap-10 lg:grid-cols-2"><div>${heading(labels.badge,escape(title),description)}<div class="my-6 flex flex-wrap gap-2">${p.tech.map(v=>`<span class="tag">${escape(v)}</span>`).join('')}</div>${button(labels.visit,p.url,true)}</div><img class="w-full rounded-xl border border-line" src="${asset(p.image)}" alt="${escape(title)}" width="1200" height="833" fetchpriority="high"></div></section><section class="wrap pb-16"><div class="grid gap-10 lg:grid-cols-2"><div><h2>${escape(labels.about)}</h2><p class="mt-6">${escape(p.overview[lang])}</p>${p.contribution ? `<h3 class="mt-8">${escape(p.contribution[lang].title)}</h3><p class="mt-4">${escape(p.contribution[lang].text)}</p>` : ''}</div><div><h2>${escape(labels.features)}</h2><ul class="mt-6 grid gap-4">${labels.items.map(v=>`<li class="flex items-center gap-3"><span class="text-accent">${icon('check')}</span>${escape(v)}</li>`).join('')}</ul></div></div></section><section class="wrap section"><h2 class="mb-8">${escape(t.related)}</h2>${cards(projects.filter(v=>v!==p).slice(0,3),lang)}</section>${cta(lang)}`;
    } else {
      const p = projects.find(p=>route === 'portfolio/'+p.slug); const i = projects.indexOf(p); title = t.projectNames[i]; description = t.projectDescriptions[i];
      content = `<section class="wrap section"><a class="mb-8 inline-flex min-h-11 items-center gap-3 text-sm text-muted hover:text-accent" href="${href(lang,'portfolio')}"><span aria-hidden="true">←</span>${escape(t.back)}</a><div class="grid items-center gap-10 lg:grid-cols-2"><div>${heading(p.tech[0],escape(title),description)}<div class="mt-6 flex flex-wrap gap-2">${p.tech.map(v=>`<span class="tag">${v}</span>`).join('')}</div><p class="mt-6 text-sm text-accent">${escape(t.demo)}</p></div><img class="w-full rounded-xl border border-line" src="${asset(p.slug+'-home.svg')}" alt="${escape(title + ' — ' + t.galleryLabels[0])}" width="800" height="500" fetchpriority="high"></div><p class="mt-10 border-l-2 border-accent pl-5 text-sm">${escape(t.caseNote)}</p><dl class="mt-12 grid gap-6 border-y border-line py-8 sm:grid-cols-3">${[[t.projectType,t.projectNames[i]],[t.technologies,p.tech.join(' / ')],[t.scope,t.projectTasks.slice(0,3).join(' · ')]].map(([key,value])=>`<div><dt class="text-sm text-muted">${escape(key)}</dt><dd class="mt-3">${escape(value)}</dd></div>`).join('')}</dl></section><section class="wrap pb-16"><div class="grid gap-10 lg:grid-cols-2"><div><p class="eyebrow">${escape(t.overview)}</p><h2>${escape(t.projectAbout)}</h2><p class="mt-6">${escape(t.caseText)}</p></div><div><h2>${escape(t.tasks)}</h2><ul class="mt-6 grid gap-4">${t.projectTasks.map(v=>`<li class="flex items-center gap-3"><span class="text-accent">${icon('check')}</span>${escape(v)}</li>`).join('')}</ul></div></div></section><section class="section border-y border-line bg-panel"><div class="wrap"><h2 class="mb-10">${escape(t.gallery)}</h2><div class="grid gap-6 md:grid-cols-2">${['home','catalog','detail','mobile'].map((v,j)=>`<figure class="panel overflow-hidden p-4"><img class="aspect-[16/10] w-full rounded-lg object-contain" src="${asset(p.slug+'-'+v+'.svg')}" alt="${escape(title+' — '+t.galleryLabels[j])}" width="800" height="500" loading="lazy"><figcaption class="mt-4 text-sm text-muted">${escape(t.galleryLabels[j])}</figcaption></figure>`).join('')}</div></div></section><section class="wrap section"><h2 class="mb-8">${escape(t.related)}</h2>${cards(projects.filter(v=>v!==p).slice(0,3),lang)}</section>${cta(lang)}`;
    }
    return layout(content,{lang,route,title,description,site});
  }
}
